version: "3.8"
services:
  db:
    image: postgres:14
    restart: unless-stopped
    environment:
      POSTGRES_USER: invoice_user
      POSTGRES_PASSWORD: mazenUser
      POSTGRES_DB: invoices_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      /bin/sh -c "./wait-for-it.sh db:5432 -- alembic upgrade head &&
                  uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/app    # <--- This is for live reload (code mounts in container)

volumes:
  pgdata:
