"""Add invoice_summary table

Revision ID: cd9701e15f1a
Revises: 87c9e225c2f9
Create Date: 2025-06-17 00:13:31.532217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd9701e15f1a'
down_revision: Union[str, Sequence[str], None] = '87c9e225c2f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('invoice_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_summary_id'), 'invoice_summary', ['id'], unique=False)
    op.execute(
        "INSERT INTO invoice_summary (total_revenue, invoice_count) VALUES (0,0)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_summary_id'), table_name='invoice_summary')
    op.drop_table('invoice_summary')
    # ### end Alembic commands ###
